# Generated by Django 3.2.25 on 2024-11-18 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('Parent', 'Parent'), ('Child', 'Child')], default='Parent', max_length=10),
        ),
    ]
