# Generated by Django 3.2.25 on 2024-10-30 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='../default_profile_zcggvy', upload_to='images/'),
        ),
    ]
