# Generated by Django 3.2.25 on 2024-11-02 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('households', '0001_initial'),
        ('profiles', '0002_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='households',
            field=models.ManyToManyField(blank=True, related_name='members', to='households.Household'),
        ),
    ]
