# Generated by Django 3.2.25 on 2024-11-02 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_profile_households'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='households',
            new_name='household',
        ),
    ]
