# Generated by Django 3.2.25 on 2024-11-02 21:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('households', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='household',
            name='household_members',
            field=models.ManyToManyField(related_name='households', to=settings.AUTH_USER_MODEL),
        ),
    ]
