# Generated by Django 3.2.25 on 2024-11-06 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('households', '0002_household_household_members'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='household',
            name='household_members',
        ),
    ]
